### ISSUE TITLE
KeyError: 'task_url'

### ISSUE THREAD

**Issue by certik** [sympy/sympy-bot-old#110] opened 2012-06-21 05:58 UTC
Right now, the sympy-bot is broken, at the end it says:

```

View log at: /tmp/sympy-bot-tmp0M_3tb/out/log
> Uploading test results
Traceback (most recent call last):
  File "/home/ondrej/usr/bin/sympy-bot", line 359, in <module>
    main()
  File "/home/ondrej/usr/bin/sympy-bot", line 141, in main
    proto=proto
  File "/home/ondrej/usr/bin/sympy-bot", line 340, in review
    report_url = reviews_sympy_org_upload(data, url_base)
  File "/home/ondrej/repos/sympy-bot/utils.py", line 210, in reviews_sympy_org_upload
    return r["task_url"]
KeyError: 'task_url'
```

and nothing gets uploaded.

**Comment by hazelnusse** [comment] 2012-06-21 07:19
I'm having the same issue.

**Comment by MichaelMayorov** [comment] 2012-06-21 07:39
@certik what command did you run?

**Comment by MichaelMayorov** [comment] 2012-06-21 07:52
I tried "./sympy-bot review 1062" and that's works well

**Comment by hazelnusse** [comment] 2012-06-21 08:26
For me it was "./sympy-bot review 1348".

I just tried "./sympy-bot -t 'echo' review 1348", and the results were posted to PR 1234 (I then deleted them), so that didn't trigger the error.  I'm rerunning the review of 1348 to see if perhaps this is something sporadic.

**Comment by hazelnusse** [comment] 2012-06-21 08:47
"./sympy-bot review 1348" just completed and uploaded fine without the "task_url" KeyError.  Must be sporadic.

**Comment by asmeurer** [comment] 2012-06-21 10:22
This is a duplicate of #64.

**Closed as completed by asmeurer** 2012-06-21 10:22 UTC
Labels: Priority-Critical
